preload = ~/.config/assets/backgrounds/cat_leaves.png

# Set the wallpaper for both monitors
wallpaper = DP-2,~/.config/assets/backgrounds/cat_leaves.png
wallpaper = DP-1,~/.config/assets/backgrounds/cat_leaves.png
